using DemoWebAPI.DB;
using DemoWebAPI.Services.Implementation;
using DemoWebAPI.Services.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DemoWebAPI.Services
{
    class Class1
    {
    }


}
namespace DemoWebAPI.Services.Interface
{
        public partial interface IProductService : IEntityService<Product>
        {
            void DoLess();
        }
    }


    namespace DemoWebAPI.Services.Implementation
    {
        /// <auto-generated>
        /// Autogenerated service class Product
        /// To extend the functioanality create another partial service class
        /// </auto-generated>
        public partial class ProductService
        {
            public void DoLess()
            {
                Console.WriteLine("Do less.......mmmm.");
            }


        }
    }

