
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// C:\Users\administrator.SPD\Documents\Visual Studio 2013\Projects\DemoWebAPI\DemoWebAPI.Services\Interface\.\.\
using DemoWebAPI.DB;
using DemoWebAPI.Repository;

namespace DemoWebAPI.Services.Interface
{
    
     /// <auto-generated>
     /// Autogenerated service class Address
     /// To extend the functioanality create another partial Interface
     /// </auto-generated>
     public partial interface IAddressService : IEntityService<Address>
     {
       
     }


     /// <auto-generated>
     /// Autogenerated service class BuildVersion
     /// To extend the functioanality create another partial Interface
     /// </auto-generated>
     public partial interface IBuildVersionService : IEntityService<BuildVersion>
     {
       
     }


     /// <auto-generated>
     /// Autogenerated service class Customer
     /// To extend the functioanality create another partial Interface
     /// </auto-generated>
     public partial interface ICustomerService : IEntityService<Customer>
     {
       
     }


     /// <auto-generated>
     /// Autogenerated service class CustomerAddress
     /// To extend the functioanality create another partial Interface
     /// </auto-generated>
     public partial interface ICustomerAddressService : IEntityService<CustomerAddress>
     {
       
     }


     /// <auto-generated>
     /// Autogenerated service class ErrorLog
     /// To extend the functioanality create another partial Interface
     /// </auto-generated>
     public partial interface IErrorLogService : IEntityService<ErrorLog>
     {
       
     }


     /// <auto-generated>
     /// Autogenerated service class Product
     /// To extend the functioanality create another partial Interface
     /// </auto-generated>
     public partial interface IProductService : IEntityService<Product>
     {
       
     }


     /// <auto-generated>
     /// Autogenerated service class ProductCategory
     /// To extend the functioanality create another partial Interface
     /// </auto-generated>
     public partial interface IProductCategoryService : IEntityService<ProductCategory>
     {
       
     }


     /// <auto-generated>
     /// Autogenerated service class ProductDescription
     /// To extend the functioanality create another partial Interface
     /// </auto-generated>
     public partial interface IProductDescriptionService : IEntityService<ProductDescription>
     {
       
     }


     /// <auto-generated>
     /// Autogenerated service class ProductModel
     /// To extend the functioanality create another partial Interface
     /// </auto-generated>
     public partial interface IProductModelService : IEntityService<ProductModel>
     {
       
     }


     /// <auto-generated>
     /// Autogenerated service class ProductModelProductDescription
     /// To extend the functioanality create another partial Interface
     /// </auto-generated>
     public partial interface IProductModelProductDescriptionService : IEntityService<ProductModelProductDescription>
     {
       
     }


     /// <auto-generated>
     /// Autogenerated service class SalesOrderDetail
     /// To extend the functioanality create another partial Interface
     /// </auto-generated>
     public partial interface ISalesOrderDetailService : IEntityService<SalesOrderDetail>
     {
       
     }


     /// <auto-generated>
     /// Autogenerated service class SalesOrderHeader
     /// To extend the functioanality create another partial Interface
     /// </auto-generated>
     public partial interface ISalesOrderHeaderService : IEntityService<SalesOrderHeader>
     {
       
     }


    
  
}
