//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebAPI.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    /*
    public static class ODataConfig
    {
            public static Microsoft.Data.Edm.IEdmModel GenerateEdmModel()
            {
                var builder = new ODataConventionModelBuilder();
    
                builder.EntitySet<ErrorLog>("ErrorLogs");
                builder.EntitySet<Address>("Addresses");
                builder.EntitySet<Customer>("Customers");
                builder.EntitySet<CustomerAddress>("CustomerAddresses");
                builder.EntitySet<Product>("Products");
                builder.EntitySet<ProductCategory>("ProductCategories");
                builder.EntitySet<ProductDescription>("ProductDescriptions");
                builder.EntitySet<ProductModel>("ProductModels");
                builder.EntitySet<ProductModelProductDescription>("ProductModelProductDescriptions");
                builder.EntitySet<SalesOrderDetail>("SalesOrderDetails");
                builder.EntitySet<SalesOrderHeader>("SalesOrderHeaders");
                builder.EntitySet<BuildVersion>("BuildVersions");
                   
                return builder.GetEdmModel();
    
            }
    }
    */
    
    public partial class DemoWebAPIContext : DbContext
    {
        public DemoWebAPIContext()
            : base("name=DemoWebAPIContext")
        {
           // this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductDescription> ProductDescriptions { get; set; }
        public virtual DbSet<ProductModel> ProductModels { get; set; }
        public virtual DbSet<ProductModelProductDescription> ProductModelProductDescriptions { get; set; }
        public virtual DbSet<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual DbSet<SalesOrderHeader> SalesOrderHeaders { get; set; }
        public virtual DbSet<BuildVersion> BuildVersions { get; set; }
    }
}
