//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class BuildVersion : BaseEntity
    {
        [Key]
        [Column(Order=1)]
        public byte SystemInformationID { get; set; }
        [Key]
        [Column(Order=2)]
        public string Database_Version { get; set; }
        [Key]
        [Column(Order=3)]
        public System.DateTime VersionDate { get; set; }
        [Key]
        [Column(Order=4)]
        public System.DateTime ModifiedDate { get; set; }
    }
}
