
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// C:\Users\administrator.SPD\Documents\Visual Studio 2013\Projects\DemoWebAPI\DemoWebAPI.Services\Implementation\.\.\
using DemoWebAPI.DB;
using DemoWebAPI.Repository;

namespace DemoWebAPI.Services.Implementation
{
    
     /// <auto-generated>
     /// Autogenerated service class Address
     /// To extend the functioanality create another partial service class
     /// </auto-generated>
     public partial class AddressService : BaseEntityService<Address>
     {
        public AddressService(IUnitOfWork unitOfWork, IRepository<Address> AddressRepository) : base(unitOfWork, AddressRepository)
        {
        }
     }


     /// <auto-generated>
     /// Autogenerated service class BuildVersion
     /// To extend the functioanality create another partial service class
     /// </auto-generated>
     public partial class BuildVersionService : BaseEntityService<BuildVersion>
     {
        public BuildVersionService(IUnitOfWork unitOfWork, IRepository<BuildVersion> BuildVersionRepository) : base(unitOfWork, BuildVersionRepository)
        {
        }
     }


     /// <auto-generated>
     /// Autogenerated service class Customer
     /// To extend the functioanality create another partial service class
     /// </auto-generated>
     public partial class CustomerService : BaseEntityService<Customer>
     {
        public CustomerService(IUnitOfWork unitOfWork, IRepository<Customer> CustomerRepository) : base(unitOfWork, CustomerRepository)
        {
        }
     }


     /// <auto-generated>
     /// Autogenerated service class CustomerAddress
     /// To extend the functioanality create another partial service class
     /// </auto-generated>
     public partial class CustomerAddressService : BaseEntityService<CustomerAddress>
     {
        public CustomerAddressService(IUnitOfWork unitOfWork, IRepository<CustomerAddress> CustomerAddressRepository) : base(unitOfWork, CustomerAddressRepository)
        {
        }
     }


     /// <auto-generated>
     /// Autogenerated service class ErrorLog
     /// To extend the functioanality create another partial service class
     /// </auto-generated>
     public partial class ErrorLogService : BaseEntityService<ErrorLog>
     {
        public ErrorLogService(IUnitOfWork unitOfWork, IRepository<ErrorLog> ErrorLogRepository) : base(unitOfWork, ErrorLogRepository)
        {
        }
     }


     /// <auto-generated>
     /// Autogenerated service class Product
     /// To extend the functioanality create another partial service class
     /// </auto-generated>
     public partial class ProductService : BaseEntityService<Product>
     {
        public ProductService(IUnitOfWork unitOfWork, IRepository<Product> ProductRepository) : base(unitOfWork, ProductRepository)
        {
        }
     }


     /// <auto-generated>
     /// Autogenerated service class ProductCategory
     /// To extend the functioanality create another partial service class
     /// </auto-generated>
     public partial class ProductCategoryService : BaseEntityService<ProductCategory>
     {
        public ProductCategoryService(IUnitOfWork unitOfWork, IRepository<ProductCategory> ProductCategoryRepository) : base(unitOfWork, ProductCategoryRepository)
        {
        }
     }


     /// <auto-generated>
     /// Autogenerated service class ProductDescription
     /// To extend the functioanality create another partial service class
     /// </auto-generated>
     public partial class ProductDescriptionService : BaseEntityService<ProductDescription>
     {
        public ProductDescriptionService(IUnitOfWork unitOfWork, IRepository<ProductDescription> ProductDescriptionRepository) : base(unitOfWork, ProductDescriptionRepository)
        {
        }
     }


     /// <auto-generated>
     /// Autogenerated service class ProductModel
     /// To extend the functioanality create another partial service class
     /// </auto-generated>
     public partial class ProductModelService : BaseEntityService<ProductModel>
     {
        public ProductModelService(IUnitOfWork unitOfWork, IRepository<ProductModel> ProductModelRepository) : base(unitOfWork, ProductModelRepository)
        {
        }
     }


     /// <auto-generated>
     /// Autogenerated service class ProductModelProductDescription
     /// To extend the functioanality create another partial service class
     /// </auto-generated>
     public partial class ProductModelProductDescriptionService : BaseEntityService<ProductModelProductDescription>
     {
        public ProductModelProductDescriptionService(IUnitOfWork unitOfWork, IRepository<ProductModelProductDescription> ProductModelProductDescriptionRepository) : base(unitOfWork, ProductModelProductDescriptionRepository)
        {
        }
     }


     /// <auto-generated>
     /// Autogenerated service class SalesOrderDetail
     /// To extend the functioanality create another partial service class
     /// </auto-generated>
     public partial class SalesOrderDetailService : BaseEntityService<SalesOrderDetail>
     {
        public SalesOrderDetailService(IUnitOfWork unitOfWork, IRepository<SalesOrderDetail> SalesOrderDetailRepository) : base(unitOfWork, SalesOrderDetailRepository)
        {
        }
     }


     /// <auto-generated>
     /// Autogenerated service class SalesOrderHeader
     /// To extend the functioanality create another partial service class
     /// </auto-generated>
     public partial class SalesOrderHeaderService : BaseEntityService<SalesOrderHeader>
     {
        public SalesOrderHeaderService(IUnitOfWork unitOfWork, IRepository<SalesOrderHeader> SalesOrderHeaderRepository) : base(unitOfWork, SalesOrderHeaderRepository)
        {
        }
     }


    
  
}
